### ISSUE TITLE
HTTP balance api error

### ISSUE THREAD

**Issue by DadiBit** [mingfunwong/all-bitcoin-private-key#18]
`api.smartbit.com.au` API doesn't exist anymore. We could either switch to a new API or make it ourselves, e.g.: adding a wrapper to the bitcoin RPC and cache the wallet balance.
One should loop over all the blocks to keep track of balances of specific wallets. The balance should be stored together with the block of the last transaction.
The two API methods used would be [`getblock`](https://developer.bitcoin.org/reference/rpc/getblock.html) and [`getrawtransaction`](https://developer.bitcoin.org/reference/rpc/getrawtransaction.html)

**Comment by AkiraTach** [comment]
Fixed it.

Thank you.
