### ISSUE TITLE
i got max speed without waiting ( sleep ) !!

### ISSUE THREAD

**Issue by canhmai** [mingfunwong/all-bitcoin-private-key#22]
combine both https://github.com/mingfunwong/all-bitcoin-private-key.git and https://github.com/Frankenmint/PKGenerator_Checker  v2Lookup.py ! edit v2Lookup.py change "https://www.bitcoinlist.io/" by
"http://localhost:4200/home?page=" will maximize the speed, napLength = 15 replaced by 0 will not have to wait.
iterLimits = 7 increments to 30 , 50 or whatever depending on your cpu .

**Comment by dvthi1902** [comment]
Can you guide me? 
(có phải VN ko? @@)
